	-- CRIAÇÃO DA TABELA DE EVENTOS
		CREATE TABLE Eventos (
			id INTEGER PRIOMARY KEY AUTOINCREMENT,
			nome TEXT NOT NULL
		);
		
		-- CRIAÇÃO DA TABELA INSCRITOS
		CREATE TABLE Inscritos (
			id INTEGER PRIMARY KEY AUTOINCREMENT,
			nome TEXT NOT NULL,
			email TEXT NOT NULL,
			link TEXT,
			evento_id INTEGER NOT NULL,
			FOREIGN KEY (evento_id) REFERENCES Eventos (id) ON DELETE CASCADE ON UPDATE CASCADE
		);
		
		--CRIAÇÃO DA TABELA EVENTOS_LINK
			CREATE TABLE Eventos_link (
			id INTEGER PRIMARY KEY AUTOINCREMENT,
			evento_id INTEGER NOT NULL,
			inscrito_id INTEGER NOT NULL,
			link TEXT,
			FOREIGN KEY (evento_id) REFERENCES Eventos (id) ON DELETE CASCADE ON UPDATE CASCADE,
			FOREIGN KEY (inscritos_id) REFERENCES Inscritos (id) ON DELETE CASCADE ON UPDATE CASCADE
		);
		